In [1]:
import numpy as np

np.arange(1, 10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
x = np.arange(1,10)
type(x)


numpy.ndarray

In [3]:
x = np.arange(1, 10, 2)
x


array([1, 3, 5, 7, 9])

In [4]:
x = np.arange(1, 10, 0.2)
x


array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [5]:
np.arange(0, 5, 0.5)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
np.linspace(1, 10, 10)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
samples, spacing = np.linspace(1, 10, retstep=True)
spacing


0.1836734693877551

In [8]:
x = np.linspace(1,10)
print("The dimension of x is:", x.ndim)
print("The shape of x is:", x.shape)


The dimension of x is: 1
The shape of x is: (50,)
